import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
import modelPath from '../models/PocketMDQSATDef.gltf'

export default function PocketMDQSAT(props) {
  const { nodes, materials } = useGLTF(modelPath)
  return (
    <group {...props} dispose={null}>
      <group scale={0.1}>
        <group position={[0, 1.304, 0.291]} rotation={[1.788, 0, 0.96]} scale={0.06}>
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1'].geometry} material={nodes['Stainless_Steel_Polished_#1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_1'].geometry} material={nodes['Stainless_Steel_Polished_#1_1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_2'].geometry} material={nodes['Stainless_Steel_Polished_#1_2'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_3'].geometry} material={nodes['Stainless_Steel_Polished_#1_3'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color17700.geometry} material={nodes.color17700.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color190190190.geometry} material={nodes.color190190190.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color24119244.geometry} material={nodes.color24119244.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color62255212.geometry} material={nodes.color62255212.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Paint_Matte_Green_#1'].geometry} material={nodes['Paint_Matte_Green_#1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color21411499.geometry} material={nodes.color21411499.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_#1'].geometry} material={nodes['Stainless_Steel_Polished_#1_#1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_4'].geometry} material={nodes['Stainless_Steel_Polished_#1_4'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_5'].geometry} material={nodes['Stainless_Steel_Polished_#1_5'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_6'].geometry} material={nodes['Stainless_Steel_Polished_#1_6'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_7'].geometry} material={nodes['Stainless_Steel_Polished_#1_7'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color254254255.geometry} material={nodes.color254254255.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color254254255_1.geometry} material={nodes.color254254255_1.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color2336247.geometry} material={nodes.color2336247.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_8'].geometry} material={nodes['Stainless_Steel_Polished_#1_8'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color254254255_2.geometry} material={nodes.color254254255_2.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Hard_Rough_Plastic_Red_#1'].geometry} material={nodes['Hard_Rough_Plastic_Red_#1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Hard_Rough_Plastic_Red_#1_1'].geometry} material={nodes['Hard_Rough_Plastic_Red_#1_1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_9'].geometry} material={nodes['Stainless_Steel_Polished_#1_9'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_10'].geometry} material={nodes['Stainless_Steel_Polished_#1_10'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_11'].geometry} material={nodes['Stainless_Steel_Polished_#1_11'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_12'].geometry} material={nodes['Stainless_Steel_Polished_#1_12'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color254254255_3.geometry} material={nodes.color254254255_3.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color254254255_4.geometry} material={nodes.color254254255_4.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_13'].geometry} material={nodes['Stainless_Steel_Polished_#1_13'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_14'].geometry} material={nodes['Stainless_Steel_Polished_#1_14'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_15'].geometry} material={nodes['Stainless_Steel_Polished_#1_15'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_16'].geometry} material={nodes['Stainless_Steel_Polished_#1_16'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_17'].geometry} material={nodes['Stainless_Steel_Polished_#1_17'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color999.geometry} material={nodes.color999.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color190190190_1.geometry} material={nodes.color190190190_1.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color190190190_2.geometry} material={nodes.color190190190_2.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_18'].geometry} material={nodes['Stainless_Steel_Polished_#1_18'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color190190190_3.geometry} material={nodes.color190190190_3.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color190190190_4.geometry} material={nodes.color190190190_4.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color190190190_5.geometry} material={nodes.color190190190_5.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_19'].geometry} material={nodes['Stainless_Steel_Polished_#1_19'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_20'].geometry} material={nodes['Stainless_Steel_Polished_#1_20'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_21'].geometry} material={nodes['Stainless_Steel_Polished_#1_21'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_22'].geometry} material={nodes['Stainless_Steel_Polished_#1_22'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_#2'].geometry} material={nodes['Stainless_Steel_Polished_#1_#2'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Anodized_Aluminum_Polished_Black_#1_#4'].geometry} material={nodes['Anodized_Aluminum_Polished_Black_#1_#5'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Anodized_Aluminum_Polished_Black_#1_#4_1'].geometry} material={nodes['Anodized_Aluminum_Polished_Black_#1_#5'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Anodized_Aluminum_Polished_Black_#1_#4_2'].geometry} material={nodes['Anodized_Aluminum_Polished_Black_#1_#5'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Anodized_Aluminum_Polished_Black_#1_#4_3'].geometry} material={nodes['Anodized_Aluminum_Polished_Black_#1_#5'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Anodized_Aluminum_Polished_Black_#1_#4_4'].geometry} material={nodes['Anodized_Aluminum_Polished_Black_#1_#5'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Anodized_Aluminum_Polished_Black_#1_#4_5'].geometry} material={nodes['Anodized_Aluminum_Polished_Black_#1_#5'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Anodized_Aluminum_Polished_Black_#1_#4_6'].geometry} material={nodes['Anodized_Aluminum_Polished_Black_#1_#5'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_23'].geometry} material={nodes['Stainless_Steel_Polished_#1_23'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_24'].geometry} material={nodes['Stainless_Steel_Polished_#1_24'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_25'].geometry} material={nodes['Stainless_Steel_Polished_#1_25'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_26'].geometry} material={nodes['Stainless_Steel_Polished_#1_26'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Anodized_Aluminum_Polished_Black_#1_#5'].geometry} material={nodes['Anodized_Aluminum_Polished_Black_#1_#5'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Anodized_Aluminum_Polished_Black_#1_#5_1'].geometry} material={nodes['Anodized_Aluminum_Polished_Black_#1_#5_1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_#3'].geometry} material={nodes['Stainless_Steel_Polished_#1_#3'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Anodized_Aluminum_Polished_Black_#1_#5_2'].geometry} material={nodes['Anodized_Aluminum_Polished_Black_#1_#5_2'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_27'].geometry} material={nodes['Stainless_Steel_Polished_#1_27'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_28'].geometry} material={nodes['Stainless_Steel_Polished_#1_28'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_29'].geometry} material={nodes['Stainless_Steel_Polished_#1_29'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_30'].geometry} material={nodes['Stainless_Steel_Polished_#1_30'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Anodized_Aluminum_Polished_Black_#1_#6'].geometry} material={nodes['Anodized_Aluminum_Polished_Black_#1_#6'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Anodized_Aluminum_Polished_Black_#1_#6_1'].geometry} material={nodes['Anodized_Aluminum_Polished_Black_#1_#6_1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_#1_1'].geometry} material={nodes['Stainless_Steel_Polished_#1_#1_1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Anodized_Aluminum_Polished_Black_#1_#6_2'].geometry} material={nodes['Anodized_Aluminum_Polished_Black_#1_#6_2'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_31'].geometry} material={nodes['Stainless_Steel_Polished_#1_31'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_32'].geometry} material={nodes['Stainless_Steel_Polished_#1_32'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_33'].geometry} material={nodes['Stainless_Steel_Polished_#1_33'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_34'].geometry} material={nodes['Stainless_Steel_Polished_#1_34'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color1781400.geometry} material={nodes.color1781400.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Paint_Matte_Black_#1'].geometry} material={nodes['Paint_Matte_Black_#1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Paint_Matte_Grey_#1'].geometry} material={nodes['Paint_Matte_Grey_#1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color254254255_5.geometry} material={nodes.color254254255_5.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_#2_1'].geometry} material={nodes['Stainless_Steel_Polished_#1_#2_1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_#1_2'].geometry} material={nodes['Stainless_Steel_Polished_#1_#1_2'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_35'].geometry} material={nodes['Stainless_Steel_Polished_#1_35'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_36'].geometry} material={nodes['Stainless_Steel_Polished_#1_36'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color646464.geometry} material={nodes.color646464.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237.geometry} material={nodes.color202209237.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_1.geometry} material={nodes.color202209237_1.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_2.geometry} material={nodes.color202209237_2.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_3.geometry} material={nodes.color202209237_3.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_4.geometry} material={nodes.color202209237_4.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_5.geometry} material={nodes.color202209237_5.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_6.geometry} material={nodes.color202209237_6.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_7.geometry} material={nodes.color202209237_7.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color255255255.geometry} material={nodes.color255255255.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_8.geometry} material={nodes.color202209237_8.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_9.geometry} material={nodes.color202209237_9.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_10.geometry} material={nodes.color202209237_10.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_11.geometry} material={nodes.color202209237_11.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_12.geometry} material={nodes.color202209237_12.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color124603.geometry} material={nodes.color124603.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_37'].geometry} material={nodes['Stainless_Steel_Polished_#1_37'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_38'].geometry} material={nodes['Stainless_Steel_Polished_#1_38'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_39'].geometry} material={nodes['Stainless_Steel_Polished_#1_39'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_40'].geometry} material={nodes['Stainless_Steel_Polished_#1_40'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Paint_Matte_Black_#1_1'].geometry} material={nodes['Paint_Matte_Black_#1_1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color646464_1.geometry} material={nodes.color646464_1.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_13.geometry} material={nodes.color202209237_13.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_14.geometry} material={nodes.color202209237_14.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_15.geometry} material={nodes.color202209237_15.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#4'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#4'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#4_1'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#4_1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#4_2'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#4_2'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#4_3'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#4_3'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#4_4'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#4_4'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_41'].geometry} material={nodes['Stainless_Steel_Polished_#1_41'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_42'].geometry} material={nodes['Stainless_Steel_Polished_#1_42'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_43'].geometry} material={nodes['Stainless_Steel_Polished_#1_43'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_44'].geometry} material={nodes['Stainless_Steel_Polished_#1_44'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Paint_Matte_Black_#1_2'].geometry} material={nodes['Paint_Matte_Black_#1_2'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color646464_2.geometry} material={nodes.color646464_2.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_16.geometry} material={nodes.color202209237_16.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_17.geometry} material={nodes.color202209237_17.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_18.geometry} material={nodes.color202209237_18.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_19.geometry} material={nodes.color202209237_19.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_20.geometry} material={nodes.color202209237_20.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_21.geometry} material={nodes.color202209237_21.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_22.geometry} material={nodes.color202209237_22.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_23.geometry} material={nodes.color202209237_23.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color255255255_1.geometry} material={nodes.color255255255_1.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_24.geometry} material={nodes.color202209237_24.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_25.geometry} material={nodes.color202209237_25.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_26.geometry} material={nodes.color202209237_26.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_27.geometry} material={nodes.color202209237_27.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_28.geometry} material={nodes.color202209237_28.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color124603_1.geometry} material={nodes.color124603_1.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color646464_3.geometry} material={nodes.color646464_3.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color255255255_2.geometry} material={nodes.color255255255_2.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color255255255_3.geometry} material={nodes.color255255255_3.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color255255255_4.geometry} material={nodes.color255255255_4.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color255255255_5.geometry} material={nodes.color255255255_5.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color255255255_6.geometry} material={nodes.color255255255_6.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#1'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#4'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#4'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#3'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#3'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#2'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#2'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_45'].geometry} material={nodes['Stainless_Steel_Polished_#1_45'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_46'].geometry} material={nodes['Stainless_Steel_Polished_#1_46'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_47'].geometry} material={nodes['Stainless_Steel_Polished_#1_47'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_48'].geometry} material={nodes['Stainless_Steel_Polished_#1_48'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Paint_Matte_Black_#1_3'].geometry} material={nodes['Paint_Matte_Black_#1_3'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color646464_4.geometry} material={nodes.color646464_4.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_29.geometry} material={nodes.color202209237_29.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_30.geometry} material={nodes.color202209237_30.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_31.geometry} material={nodes.color202209237_31.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_32.geometry} material={nodes.color202209237_32.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_33.geometry} material={nodes.color202209237_33.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_34.geometry} material={nodes.color202209237_34.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_35.geometry} material={nodes.color202209237_35.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_36.geometry} material={nodes.color202209237_36.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color255255255_7.geometry} material={nodes.color255255255_7.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_37.geometry} material={nodes.color202209237_37.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_38.geometry} material={nodes.color202209237_38.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_39.geometry} material={nodes.color202209237_39.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_40.geometry} material={nodes.color202209237_40.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_41.geometry} material={nodes.color202209237_41.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color124603_2.geometry} material={nodes.color124603_2.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#6'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#6'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#7'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#7'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#8'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#8'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#9'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#9'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#5'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#5'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_49'].geometry} material={nodes['Stainless_Steel_Polished_#1_49'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_50'].geometry} material={nodes['Stainless_Steel_Polished_#1_50'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_51'].geometry} material={nodes['Stainless_Steel_Polished_#1_51'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_52'].geometry} material={nodes['Stainless_Steel_Polished_#1_52'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Paint_Matte_Black_#1_4'].geometry} material={nodes['Paint_Matte_Black_#1_4'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#6_1'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#6_1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#6_2'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#6_2'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#6_3'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#6_3'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#6_4'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#6_4'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#6_5'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#6_5'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#6_6'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#6_6'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_42.geometry} material={nodes.color202209237_42.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_43.geometry} material={nodes.color202209237_43.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color124603_3.geometry} material={nodes.color124603_3.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color646464_5.geometry} material={nodes.color646464_5.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_44.geometry} material={nodes.color202209237_44.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_45.geometry} material={nodes.color202209237_45.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_46.geometry} material={nodes.color202209237_46.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_47.geometry} material={nodes.color202209237_47.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_48.geometry} material={nodes.color202209237_48.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_49.geometry} material={nodes.color202209237_49.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_50.geometry} material={nodes.color202209237_50.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_51.geometry} material={nodes.color202209237_51.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color255255255_8.geometry} material={nodes.color255255255_8.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_52.geometry} material={nodes.color202209237_52.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_53.geometry} material={nodes.color202209237_53.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_54.geometry} material={nodes.color202209237_54.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color646464_6.geometry} material={nodes.color646464_6.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color255255255_9.geometry} material={nodes.color255255255_9.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color255255255_10.geometry} material={nodes.color255255255_10.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color255255255_11.geometry} material={nodes.color255255255_11.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color255255255_12.geometry} material={nodes.color255255255_12.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color255255255_13.geometry} material={nodes.color255255255_13.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#7_1'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_#5_#1_#4_#7_1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_1'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_53'].geometry} material={nodes['Stainless_Steel_Polished_#1_53'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_54'].geometry} material={nodes['Stainless_Steel_Polished_#1_54'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_55'].geometry} material={nodes['Stainless_Steel_Polished_#1_55'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_56'].geometry} material={nodes['Stainless_Steel_Polished_#1_56'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Paint_Matte_Black_#1_5'].geometry} material={nodes['Paint_Matte_Black_#1_5'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_#1_3'].geometry} material={nodes['Stainless_Steel_Polished_#1_#1_3'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Hard_Rough_Plastic_Red_#1_#1'].geometry} material={nodes['Hard_Rough_Plastic_Red_#1_#1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Hard_Rough_Plastic_Red_#1_#1_#1'].geometry} material={nodes['Hard_Rough_Plastic_Red_#1_#1_#1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Plastic_Acrylic_(Dispersive)_#1_2'].geometry} material={nodes['Plastic_Acrylic_(Dispersive)_#1_2'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_55.geometry} material={nodes.color202209237_55.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_56.geometry} material={nodes.color202209237_56.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_57.geometry} material={nodes.color202209237_57.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_58.geometry} material={nodes.color202209237_58.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_59.geometry} material={nodes.color202209237_59.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_60.geometry} material={nodes.color202209237_60.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_61.geometry} material={nodes.color202209237_61.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_62.geometry} material={nodes.color202209237_62.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_#4'].geometry} material={nodes['Stainless_Steel_Polished_#1_#4'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_63.geometry} material={nodes.color202209237_63.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_64.geometry} material={nodes.color202209237_64.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color202209237_65.geometry} material={nodes.color202209237_65.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Hard_Rough_Plastic_Red_#1_#1_1'].geometry} material={nodes['Hard_Rough_Plastic_Red_#1_#1_1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Hard_Rough_Plastic_Red_#1_#1_#1_1'].geometry} material={nodes['Hard_Rough_Plastic_Red_#1_#1_#1_1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Hard_Rough_Plastic_Red_#1_#1_#2'].geometry} material={nodes['Hard_Rough_Plastic_Red_#1_#1_#2'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes.color999_1.geometry} material={nodes.color999_1.material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_57'].geometry} material={nodes['Stainless_Steel_Polished_#1_57'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_58'].geometry} material={nodes['Stainless_Steel_Polished_#1_58'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_59'].geometry} material={nodes['Stainless_Steel_Polished_#1_59'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_60'].geometry} material={nodes['Stainless_Steel_Polished_#1_60'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_61'].geometry} material={nodes['Stainless_Steel_Polished_#1_61'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_62'].geometry} material={nodes['Stainless_Steel_Polished_#1_62'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_#3_1'].geometry} material={nodes['Stainless_Steel_Polished_#1_#3_1'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_63'].geometry} material={nodes['Stainless_Steel_Polished_#1_63'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_64'].geometry} material={nodes['Stainless_Steel_Polished_#1_64'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_65'].geometry} material={nodes['Stainless_Steel_Polished_#1_65'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_66'].geometry} material={nodes['Stainless_Steel_Polished_#1_66'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_67'].geometry} material={nodes['Stainless_Steel_Polished_#1_67'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_68'].geometry} material={nodes['Stainless_Steel_Polished_#1_68'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_69'].geometry} material={nodes['Stainless_Steel_Polished_#1_69'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_70'].geometry} material={nodes['Stainless_Steel_Polished_#1_70'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_71'].geometry} material={nodes['Stainless_Steel_Polished_#1_71'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_72'].geometry} material={nodes['Stainless_Steel_Polished_#1_72'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_73'].geometry} material={nodes['Stainless_Steel_Polished_#1_73'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_74'].geometry} material={nodes['Stainless_Steel_Polished_#1_74'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_75'].geometry} material={nodes['Stainless_Steel_Polished_#1_75'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Hard_Rough_Plastic_Red_#1_2'].geometry} material={nodes['Hard_Rough_Plastic_Red_#1_2'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Hard_Rough_Plastic_Red_#1_3'].geometry} material={nodes['Hard_Rough_Plastic_Red_#1_3'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Hard_Rough_Plastic_Red_#1_4'].geometry} material={nodes['Hard_Rough_Plastic_Red_#1_4'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Hard_Rough_Plastic_Red_#1_5'].geometry} material={nodes['Hard_Rough_Plastic_Red_#1_5'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_76'].geometry} material={nodes['Stainless_Steel_Polished_#1_76'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_77'].geometry} material={nodes['Stainless_Steel_Polished_#1_77'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_78'].geometry} material={nodes['Stainless_Steel_Polished_#1_78'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_79'].geometry} material={nodes['Stainless_Steel_Polished_#1_79'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_80'].geometry} material={nodes['Stainless_Steel_Polished_#1_80'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_81'].geometry} material={nodes['Stainless_Steel_Polished_#1_81'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_82'].geometry} material={nodes['Stainless_Steel_Polished_#1_82'].material} />
          <mesh matrixWorldNeedsUpdate={true} geometry={nodes['Stainless_Steel_Polished_#1_83'].geometry} material={nodes['Stainless_Steel_Polished_#1_83'].material} />
        </group>
      </group>
      <PerspectiveCamera makeDefault={false} far={41.656} near={18.054} fov={39.598} position={[-5.931, 14.292, 29.044]} rotation={[-0.156, -0.288, -0.045]} />
      <PerspectiveCamera makeDefault={false} far={43.689} near={18.03} fov={39.598} position={[-14.916, 8.183, 27.022]} rotation={[0.036, -0.556, 0.019]} />
      <PerspectiveCamera makeDefault={false} far={26.243} near={0.001} fov={39.598} position={[-3.018, 12.458, 14.338]} rotation={[0.093, -0.632, 0.055]} />
      <PerspectiveCamera makeDefault={false} far={38.589} near={12.002} fov={39.598} position={[18.725, 18.193, 16.106]} rotation={[-0.261, 0.62, 0.154]} />
    </group>
  )
}